// SPDX-License-Identifier: CC0-1.0
// Public-domain example code (CC0) - see LICENSE. The CAS BACnet Stack itself is
// a separate, commercially licensed product and is not covered by CC0.
// =============================================================================
// BACnet Profile Example - B-GW (Gateway) - C++
//
// This example implements the BACnet "B-GW" (Gateway) device profile with the
// CAS BACnet Stack. It is the B-ASC (Application Specific Controller) example
// (DS-RP-B + DS-WP-B + DM-DCC-B, plus discovery) PLUS one BACnet virtual
// network carrying ONE virtual BACnet device - GW-VN-B (Annex K.7.1: a
// gateway represents a non-BACnet, or otherwise not-directly-reachable, device
// as a virtual BACnet device on a virtual network behind it).
//
// A B-GW is a device that:
//
//     DS-RP-B    - respond to ReadProperty requests (on itself AND on the
//                  virtual device it represents),
//     DS-WP-B    - allow other devices to WriteProperty its objects,
//     DM-DDB-B   - answer Who-Is with I-Am (both the gateway's own I-Am and
//                  the virtual device's),
//     DM-DOB-B   - answer Who-Has,
//     DM-DCC-B   - respond to DeviceCommunicationControl,
//     GW-VN-B    - represent a device it is gatewaying for as a virtual
//                  BACnet device on a virtual network.
//
// plus discovery. This example does NOT implement DM-LM-B or NM-RC-B (unlike
// its seed, B-RTR) - a gateway is not itself a physical inter-network router,
// and does not claim to be one; see the header comment on B-RTR-CPP for why
// that pattern does not apply here.
//
// The GATEWAY device keeps the same base objects as B-ASC - three read-only
// sensor inputs and three commandable outputs a client drives with
// WriteProperty:
//
//     Device 389019            "Rainbow"           (instance configurable with --deviceID)
//     Analog Input  1          "Bronze"            (REAL, degrees Celsius; read-only)
//     Binary Input  1          "Emerald"           (active / inactive; read-only)
//     Multi-State Input 1      "Hot Pink"          (state 1..3; read-only)
//     Analog Output 1          "Chartreuse"        (REAL setpoint; WRITABLE, commandable)
//     Binary Output 1          "Fuchsia"           (active / inactive; WRITABLE, commandable)
//     Multi-State Output 1     "Indigo"            (state 1..3; WRITABLE, commandable)
//     Network Port 1           "Vermilion"         (the BACnet/IP port - required)
//
// Behind it, on virtual network VIRTUAL_NETWORK_NUMBER, sits ONE VIRTUAL
// DEVICE - the thing this gateway is actually gatewaying:
//
//     Device 389119            "Rainbow (virtual)" (docs/colour-table.md: gateway
//                                                    instance + 100)
//     Analog Input  1          "Bronze"            (REAL, degrees Celsius; read-only;
//                                                    its OWN value, independent of the
//                                                    gateway's Analog Input 1 above)
//
// F-GATEWAY: BACnetStack_AddVirtualNetwork(gatewayInstance, network,
// virtualNetworkPortInstance) turns the gateway device into a virtual router
// and creates the Network Port object for that virtual network;
// BACnetStack_AddDeviceToVirtualNetwork(virtualDeviceInstance, network) then
// adds the virtual device itself. From that point on the virtual device is a
// full BACnet device as far as the rest of the API is concerned - it gets its
// own BACnetStack_AddDevice-shaped identity and BACnetStack_AddObject calls
// name it directly as the deviceInstance parameter, exactly like the real
// gateway device. The Get/SetProperty callbacks below dispatch on
// deviceInstance for this reason - the virtual device answers indistinguishably
// from a second, separate example process, except that it shares the
// gateway's one UDP socket and Network Port.
//
// Output objects are COMMANDABLE: their Present_Value is driven by a 16-slot
// BACnet Priority_Array, exactly as in B-SA/B-ASC/B-RTR. See GetCommandable()
// etc. below - unchanged from those examples.
//
// To be a conformant BACnet device (Protocol_Revision 24) each object must
// expose its full set of REQUIRED properties. Most are generated by the stack
// (Object_Identifier, Object_Type, Status_Flags, Object_List, Protocol_*).
//
// Interactive keys (handled by the shared helper): h = help, q = quit,
// up/down = nudge the GATEWAY's Analog Input 1 by +/-1.1, r = re-send I-Am for
// BOTH devices (gateway + virtual) now, instead of waiting for the one sent at
// start-up (common/ 2.4.0+ - the same key B-RTR claimed for "routing/gateway
// examples" in docs/menu-keys.md; this example repurposes its ACTION to a
// plain I-Am re-announce rather than I-Am-Router-To-Network, since a gateway
// is not a router and does not send network-layer router messages).
// Command line: --port <n>, --deviceID <n> (the GATEWAY's instance only - the
// virtual device's instance is fixed at gatewayInstance + 100, per
// docs/colour-table.md, and moves with it only if you also change the
// VIRTUAL_DEVICE_INSTANCE constant below).
//
// All the UDP/stack plumbing lives in common/CASExampleHelper so this file can
// stay focused on the BACnet logic.
// =============================================================================

#include "CASExampleHelper.h"
#include "CASBACnetStackExampleConstants.h"
#include "CASBACnetStackAdapter.h" // the CAS BACnet Stack C API (BACnetStack_*); call
                                    // LoadBACnetFunctions() before any BACnetStack_* call -
                                    // see the top of main() below.

#include <stdio.h>
#include <string.h>
#include <string>

#if defined(_WIN32)
#include <windows.h> // Sleep()
#else
#include <unistd.h>  // usleep()
#endif

using namespace CASBACnetStackExampleConstants;

// -----------------------------------------------------------------------------
// 1. Example + device configuration
// -----------------------------------------------------------------------------
static const char* APP_NAME = "BACnet B-GW (Gateway) Example - C++";
static const char* APP_VERSION = "1.0.1";

// The GATEWAY device instance. BACnet requires this to be configurable, so it
// defaults to 389019 (docs/colour-table.md) and can be overridden on the
// command line with --deviceID. Keep it configurable in your product: it
// must be unique across the internetwork.
static uint32_t g_deviceInstance = 389019;

// The VIRTUAL device instance - the gateway's number + 100, per
// docs/colour-table.md ("A virtual device behind a gateway (B-GW) uses the
// gateway's number + 100"). NOT overridden by --deviceID: --deviceID only
// renumbers the gateway itself, matching every other example's --deviceID
// contract (it configures THIS device, not something behind it).
// CHANGE BEFORE YOU SHIP: must also be unique across the whole BACnet
// internetwork, exactly like the gateway's own instance - two devices with
// colliding instances is a spec violation regardless of which one they are.
static const uint32_t VIRTUAL_DEVICE_INSTANCE = 389119;
// The virtual device's Object_Name. CHANGE BEFORE YOU SHIP, and see the
// warning on DEVICE_NAME below - it applies here too.
static const char* VIRTUAL_DEVICE_NAME = "Rainbow (virtual)";

// The virtual network the virtual device lives on, and the Network Port
// object instance created for it by BACnetStack_AddVirtualNetwork. Neither is
// a real, wire-configured BACnet/IP network - see BACnetStack_AddVirtualNetwork's
// doc comment. 100 avoids the physical Network Port's own (unconfigured,
// quality UNKNOWN, effectively 0) network number.
// CHANGE BEFORE YOU SHIP: must be unique among every network number (real or
// virtual) on the internetwork, same as a device instance must be unique
// among device instances.
static const uint16_t VIRTUAL_NETWORK_NUMBER = 100;
static const uint32_t VIRTUAL_NETWORK_PORT_INSTANCE = 2; // "Network Port 1" (Vermilion) is 1

// ---- Device identity: CHANGE ALL OF THIS BEFORE YOU SHIP --------------------
// Everything in this block is read by clients and shown to the operator in every
// discovery tool on the network. Left as-is, your product will appear on a real
// site announcing itself as a Chipkin demo. None of it is cosmetic:
// Object_Name must be unique across the BACnet internetwork, and Model_Name /
// Vendor_Identifier are what a building operator uses to identify your device.
// -----------------------------------------------------------------------------

// Your BACnet Vendor Identifier. 389 = Chipkin Automation Systems; change this
// to YOUR company's vendor ID before shipping a product. Vendor IDs are assigned
// by ASHRAE - request one (free) at https://bacnet.org/assigned-vendor-ids/.
// Update VENDOR_NAME below to match. The virtual device shares the same vendor.
static const uint32_t VENDOR_IDENTIFIER = 389;

// The GATEWAY's Object_Name.
//
// THIS IS THE ONE THAT WILL BITE YOU. Object_Name must be unique across the
// whole BACnet internetwork, and here it is a COMPILE-TIME constant. The
// device instance is runtime-configurable via --deviceID, so it is easy to
// ship two units, configure their instances correctly, and still have BOTH
// announce Object_Name "Rainbow" - a spec violation, and a hard BTL failure.
// The SAME is true of VIRTUAL_DEVICE_NAME below: it is fixed at compile time
// too, and every unit's virtual device would collide right along with the
// gateway's. In a real product BOTH names must be per-unit configurable:
// derive them from a serial number, DIP switches, a config file, or add a
// --deviceName argument.
static const char* DEVICE_NAME = "Rainbow";

// The GATEWAY's Description. Change it to what YOUR device actually is; this
// string describes this tutorial.
static const char* DEVICE_DESCRIPTION =
    "Chipkin CAS BACnet Stack example - B-GW (Gateway) profile. Demonstrates "
    "DS-RP-B + DS-WP-B + DM-DDB-B + DM-DOB-B + DM-DCC-B + GW-VN-B: a gateway "
    "device that represents one virtual BACnet device on a virtual network "
    "behind it.";
// The VIRTUAL device's Description. Change it to what your gatewayed device
// actually is.
static const char* VIRTUAL_DEVICE_DESCRIPTION =
    "Chipkin CAS BACnet Stack example - B-GW (Gateway) profile. A VIRTUAL "
    "BACnet device (GW-VN-B), modelled behind Device 389019 on virtual "
    "network 100, with its own Analog Input.";

// Device identity strings (read by clients, and used to populate I-Am). The
// virtual device answers with its own Model_Name so a client can tell the two
// devices apart in a discovery tool even though they share one IP/UDP port.
//   VENDOR_NAME        - your company name; must match VENDOR_IDENTIFIER above.
//   MODEL_NAME          - your GATEWAY's model designation, read by a building
//                          operator to identify it in a discovery tool.
//   VIRTUAL_MODEL_NAME  - the model designation for the device you gateway.
static const char* VENDOR_NAME = "Chipkin Automation Systems";
static const char* MODEL_NAME = "CAS BACnet Stack Example - B-GW";
static const char* VIRTUAL_MODEL_NAME = "CAS BACnet Stack Example - B-GW (virtual device)";

// DeviceCommunicationControl password. A management station may include a password
// with a DeviceCommunicationControl (or ReinitializeDevice) request; the device
// accepts the command only if it matches. Set to NULL/empty to accept any request
// (no password required). Change this to your device's secret before shipping.
static const char* DCC_PASSWORD = "";  // "" = no password required

// Application_Software_Version (12) is just APP_VERSION - one source of
// truth, shared by both devices, so it can never drift from what
// --version/the startup banner prints.
//
// Firmware_Revision (44) is meant to name the underlying platform/stack,
// not this example's own version - built at runtime from the CAS BACnet
// Stack's own BACnetStack_GetAPIMajorVersion()/etc. (the same 4 calls
// common/CASExampleHelper.cpp's PrintVersion() already uses for the
// startup banner's "CAS BACnet Stack version: X.Y.Z.W" line), so it can
// never go stale either - see g_firmwareRevision below, populated once
// right after LoadBACnetFunctions() succeeds (those functions are what
// the version getters themselves are, so they must be loaded first).
static std::string g_firmwareRevision;

// The GATEWAY's sensor objects (all instance 1) and their colour names.
static const uint32_t ANALOG_INPUT_INSTANCE = 1;       // "Bronze"
static const uint32_t BINARY_INPUT_INSTANCE = 1;       // "Emerald"
static const uint32_t MULTI_STATE_INPUT_INSTANCE = 1;  // "Hot Pink"
static const uint32_t MULTI_STATE_INPUT_NUMBER_OF_STATES = 3;

// The VIRTUAL device's own Analog Input 1 ("Bronze") - a SEPARATE object,
// SEPARATE value, living under VIRTUAL_DEVICE_INSTANCE rather than
// g_deviceInstance. Every Get/SetProperty callback below dispatches on
// deviceInstance first for exactly this reason - object type + instance alone
// is not enough to tell the two devices' identically-numbered objects apart.
static const uint32_t VIRTUAL_ANALOG_INPUT_INSTANCE = 1; // "Bronze"
static float g_virtualAnalogInput1Value = 19.0f;

// The Network Port object - every BACnet device must have one. It represents
// the BACnet/IP port the GATEWAY communicates on; the virtual device is
// reached through this SAME port (it has no socket of its own - see
// BACnetStack_AddVirtualNetwork's doc comment).
static const uint32_t NETWORK_PORT_INSTANCE = 1;       // "Vermilion"
static const uint32_t MAX_APDU_LENGTH = 1476;          // BACnet/IP APDU length

// BACnet/IP addressing the Network Port reports. The IP address and subnet mask
// are filled in at start-up from the host's primary interface; the gateway is
// left unset (0.0.0.0) for this example. The stack also uses IP_Address +
// BACnet_IP_UDP_Port to build the port's MAC_Address automatically.
static uint8_t g_ipAddress[4] = { 0, 0, 0, 0 };
static uint8_t g_ipSubnetMask[4] = { 0, 0, 0, 0 };
static uint8_t g_ipDefaultGateway[4] = { 0, 0, 0, 0 };
static uint16_t g_bacnetIpUdpPort = 47808;

// Analog Input 1's live present value (degrees Celsius). Starts at 21.5 and is
// nudged by the up/down arrow keys. A real sensor would update this from
// hardware instead. This is the GATEWAY's own value; the virtual device's
// Analog Input 1 (g_virtualAnalogInput1Value above) is independent.
static float g_analogInput1Value = 21.5f;

// The GATEWAY's commandable OUTPUT objects (all instance 1) and their colour
// names. Inherited verbatim from B-SA/B-ASC/B-RTR: clients drive them with
// WriteProperty (DS-WP-B). The virtual device has none - it exists to
// demonstrate GW-VN-B (a represented device), not F-OUTPUTS a second time.
static const uint32_t ANALOG_OUTPUT_INSTANCE = 1;        // "Chartreuse"
static const uint32_t BINARY_OUTPUT_INSTANCE = 1;        // "Fuchsia"
static const uint32_t MULTI_STATE_OUTPUT_INSTANCE = 1;   // "Indigo"
static const uint32_t MULTI_STATE_OUTPUT_NUMBER_OF_STATES = 3;
static const uint32_t BACNET_PRIORITY_ARRAY_SIZE = 16;

// A BACnet commandable value: a 16-slot Priority_Array plus a Relinquish_Default.
// Each slot is either null (relinquished) or holds a commanded value. A real
// device would map the resolved Present_Value onto its physical output; here we
// just store the commands. The values are kept as double and cast per object
// type (REAL for AO, 0/1 for BO, state number for MSO).
struct Commandable {
    bool isSet[16];          // is slot i (1..16) commanded?
    double value[16];        // the commanded value at slot i
    double relinquishDefault;
};

static Commandable g_analogOutput = { { false }, { 0 }, 20.0 }; // setpoint, default 20.0 C
static Commandable g_binaryOutput = { { false }, { 0 }, 0.0 };  // default inactive (0)
static Commandable g_multiStateOutput = { { false }, { 0 }, 1.0 }; // default state 1

static uint8_t EffectivePriority(uint8_t priority) {
    return (priority >= 1 && priority <= BACNET_PRIORITY_ARRAY_SIZE) ? priority : 16;
}

static void CommandWrite(Commandable* c, uint8_t priority, double value) {
    const uint8_t p = EffectivePriority(priority);
    c->isSet[p - 1] = true;
    c->value[p - 1] = value;
}

static void CommandRelinquish(Commandable* c, uint8_t priority) {
    const uint8_t p = EffectivePriority(priority);
    c->isSet[p - 1] = false;
}

// Resolve which Commandable an (deviceInstance, objectType, objectInstance) maps
// to, or NULL. Only the GATEWAY has commandable outputs.
static Commandable* GetCommandable(uint32_t deviceInstance, uint16_t objectType, uint32_t objectInstance) {
    if (deviceInstance != g_deviceInstance) {
        return NULL;
    }
    if (objectType == OBJECT_TYPE_ANALOG_OUTPUT && objectInstance == ANALOG_OUTPUT_INSTANCE) {
        return &g_analogOutput;
    }
    if (objectType == OBJECT_TYPE_BINARY_OUTPUT && objectInstance == BINARY_OUTPUT_INSTANCE) {
        return &g_binaryOutput;
    }
    if (objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT && objectInstance == MULTI_STATE_OUTPUT_INSTANCE) {
        return &g_multiStateOutput;
    }
    return NULL;
}

static bool ReadPrioritySlot(const Commandable* c, uint32_t propertyIdentifier,
                             bool useArrayIndex, uint32_t propertyArrayIndex,
                             bool* slotIsSet, double* slotValue) {
    if (propertyIdentifier != PROPERTY_IDENTIFIER_PRIORITY_ARRAY || !useArrayIndex ||
        propertyArrayIndex < 1 || propertyArrayIndex > BACNET_PRIORITY_ARRAY_SIZE) {
        return false;
    }
    *slotIsSet = c->isSet[propertyArrayIndex - 1];
    *slotValue = c->value[propertyArrayIndex - 1];
    return true;
}

// -----------------------------------------------------------------------------
// 2. Property "get" callbacks. See B-ASC's main.cpp for the full essay on the
// errorCode out-parameter and the decline-and-fabricate fallback; the same
// rules apply here unchanged. The only NEW material below is dispatching on
// deviceInstance to serve TWO devices (gateway + virtual) from one process.
// -----------------------------------------------------------------------------

bool GetPropertyReal(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     float* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)errorCode;
    if (deviceInstance == VIRTUAL_DEVICE_INSTANCE) {
        if (objectType == OBJECT_TYPE_ANALOG_INPUT &&
            objectInstance == VIRTUAL_ANALOG_INPUT_INSTANCE &&
            propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = g_virtualAnalogInput1Value;
            return true;
        }
        return false;
    }
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_ANALOG_INPUT &&
        objectInstance == ANALOG_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        *value = g_analogInput1Value;
        return true;
    }
    const Commandable* c = GetCommandable(deviceInstance, objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_ANALOG_OUTPUT) {
        bool slotIsSet = false;
        double slotValue = 0.0;
        if (ReadPrioritySlot(c, propertyIdentifier, useArrayIndex, propertyArrayIndex,
                             &slotIsSet, &slotValue)) {
            if (!slotIsSet) {
                return false;
            }
            *value = (float)slotValue;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT) {
            *value = (float)c->relinquishDefault;
            return true;
        }
    }
    return false;
}

bool GetPropertyEnumerated(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           uint32_t* value, const bool useArrayIndex,
                           const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)errorCode;
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance == VIRTUAL_DEVICE_INSTANCE) {
        if (objectType == OBJECT_TYPE_ANALOG_INPUT &&
            objectInstance == VIRTUAL_ANALOG_INPUT_INSTANCE &&
            propertyIdentifier == PROPERTY_IDENTIFIER_UNITS) {
            *value = ENGINEERING_UNITS_DEGREES_CELSIUS;
            return true;
        }
        return false;
    }
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_BINARY_INPUT &&
        objectInstance == BINARY_INPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = 0; // inactive - the series-wide starting value
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_POLARITY) {
            *value = POLARITY_NORMAL;
            return true;
        }
    }
    const Commandable* c = GetCommandable(deviceInstance, objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_BINARY_OUTPUT) {
        bool slotIsSet = false;
        double slotValue = 0.0;
        if (ReadPrioritySlot(c, propertyIdentifier, useArrayIndex, propertyArrayIndex,
                             &slotIsSet, &slotValue)) {
            if (!slotIsSet) {
                return false;
            }
            *value = (uint32_t)slotValue;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT) {
            *value = (uint32_t)c->relinquishDefault;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_POLARITY) {
            *value = POLARITY_NORMAL;
            return true;
        }
    }
    if (propertyIdentifier == PROPERTY_IDENTIFIER_UNITS &&
        ((objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == ANALOG_INPUT_INSTANCE) ||
         (objectType == OBJECT_TYPE_ANALOG_OUTPUT && objectInstance == ANALOG_OUTPUT_INSTANCE))) {
        *value = ENGINEERING_UNITS_DEGREES_CELSIUS;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT &&
        propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_MODE) {
        *value = BACNET_IP_MODE_NORMAL;
        return true;
    }
    return false;
}

bool GetPropertyUnsignedInteger(const uint32_t deviceInstance, const uint16_t objectType,
                                const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                uint32_t* value, const bool useArrayIndex,
                                const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)errorCode;
    if (deviceInstance == VIRTUAL_DEVICE_INSTANCE) {
        if (objectType == OBJECT_TYPE_DEVICE && objectInstance == VIRTUAL_DEVICE_INSTANCE &&
            propertyIdentifier == PROPERTY_IDENTIFIER_VENDOR_IDENTIFIER) {
            *value = VENDOR_IDENTIFIER;
            return true;
        }
        return false;
    }
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = 1;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_NUMBER_OF_STATES) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT &&
            useArrayIndex && propertyArrayIndex == 0) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES;
            return true;
        }
    }
    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance &&
        propertyIdentifier == PROPERTY_IDENTIFIER_VENDOR_IDENTIFIER) {
        *value = VENDOR_IDENTIFIER;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_APDU_LENGTH) {
            *value = MAX_APDU_LENGTH;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_REFERENCE_PORT) {
            *value = NETWORK_PORT_REFERENCE_PORT_NONE;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT) {
            *value = g_bacnetIpUdpPort;
            return true;
        }
    }
    const Commandable* c = GetCommandable(deviceInstance, objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT) {
        bool slotIsSet = false;
        double slotValue = 0.0;
        if (ReadPrioritySlot(c, propertyIdentifier, useArrayIndex, propertyArrayIndex,
                             &slotIsSet, &slotValue)) {
            if (!slotIsSet) {
                return false;
            }
            *value = (uint32_t)slotValue;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT) {
            *value = (uint32_t)c->relinquishDefault;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_NUMBER_OF_STATES) {
            *value = MULTI_STATE_OUTPUT_NUMBER_OF_STATES;
            return true;
        }
    }
    return false;
}

bool GetPropertyBool(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     bool* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)errorCode;
    if (deviceInstance == VIRTUAL_DEVICE_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_OUT_OF_SERVICE &&
            objectType == OBJECT_TYPE_ANALOG_INPUT &&
            objectInstance == VIRTUAL_ANALOG_INPUT_INSTANCE) {
            *value = false;
            return true;
        }
        return false;
    }
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    const Commandable* c = GetCommandable(deviceInstance, objectType, objectInstance);
    if (c != NULL && propertyIdentifier == PROPERTY_IDENTIFIER_PRIORITY_ARRAY &&
        useArrayIndex && propertyArrayIndex >= 1 &&
        propertyArrayIndex <= BACNET_PRIORITY_ARRAY_SIZE) {
        *value = !c->isSet[propertyArrayIndex - 1];
        return true;
    }
    // Out_Of_Service: false for every input/output object AND the Network Port.
    if (propertyIdentifier == PROPERTY_IDENTIFIER_OUT_OF_SERVICE &&
        (objectType == OBJECT_TYPE_ANALOG_INPUT ||
         objectType == OBJECT_TYPE_BINARY_INPUT ||
         objectType == OBJECT_TYPE_MULTI_STATE_INPUT ||
         objectType == OBJECT_TYPE_ANALOG_OUTPUT ||
         objectType == OBJECT_TYPE_BINARY_OUTPUT ||
         objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT ||
         objectType == OBJECT_TYPE_NETWORK_PORT)) {
        *value = false;
        return true;
    }
    return false;
}

// OCTET STRING - the Network Port's addressing. Only the GATEWAY has a
// Network Port object; the virtual network's Network Port
// (VIRTUAL_NETWORK_PORT_INSTANCE) is created and fully populated internally by
// BACnetStack_AddVirtualNetwork - this callback is never consulted for it.
bool GetPropertyOctetString(const uint32_t deviceInstance, const uint16_t objectType,
                            const uint32_t objectInstance, const uint32_t propertyIdentifier,
                            uint8_t* value, uint32_t* valueElementCount,
                            const uint32_t maxElementCount, const bool useArrayIndex,
                            const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    if (deviceInstance != g_deviceInstance ||
        objectType != OBJECT_TYPE_NETWORK_PORT ||
        objectInstance != NETWORK_PORT_INSTANCE ||
        maxElementCount < 4) {
        return false;
    }
    const uint8_t* source = NULL;
    switch (propertyIdentifier) {
        case PROPERTY_IDENTIFIER_IP_ADDRESS:         source = g_ipAddress; break;
        case PROPERTY_IDENTIFIER_IP_SUBNET_MASK:     source = g_ipSubnetMask; break;
        case PROPERTY_IDENTIFIER_IP_DEFAULT_GATEWAY: source = g_ipDefaultGateway; break;
        default: return false;
    }
    memcpy(value, source, 4);
    *valueElementCount = 4;
    return true;
}

static bool ReturnCharacterString(const char* text, char* value,
                                  uint32_t* valueElementCount,
                                  const uint32_t maxElementCount,
                                  uint8_t* encodingType) {
    uint32_t length = (uint32_t)strlen(text);
    if (length > maxElementCount) {
        length = maxElementCount;
    }
    memcpy(value, text, length);
    *valueElementCount = length;
    *encodingType = CHARACTER_STRING_ENCODING_UTF8;
    return true;
}

bool GetPropertyCharString(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           char* value, uint32_t* valueElementCount,
                           const uint32_t maxElementCount, uint8_t* encodingType,
                           const bool useArrayIndex, const uint32_t propertyArrayIndex,
                           uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;

    // --- The VIRTUAL device -------------------------------------------------
    if (deviceInstance == VIRTUAL_DEVICE_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_OBJECT_NAME) {
            if (objectType == OBJECT_TYPE_DEVICE && objectInstance == VIRTUAL_DEVICE_INSTANCE) {
                return ReturnCharacterString(VIRTUAL_DEVICE_NAME, value, valueElementCount, maxElementCount, encodingType);
            }
            if (objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == VIRTUAL_ANALOG_INPUT_INSTANCE) {
                return ReturnCharacterString("Bronze", value, valueElementCount, maxElementCount, encodingType);
            }
        }
        if (objectType == OBJECT_TYPE_DEVICE && objectInstance == VIRTUAL_DEVICE_INSTANCE) {
            switch (propertyIdentifier) {
                case PROPERTY_IDENTIFIER_DESCRIPTION:
                    return ReturnCharacterString(VIRTUAL_DEVICE_DESCRIPTION, value, valueElementCount, maxElementCount, encodingType);
                case PROPERTY_IDENTIFIER_VENDOR_NAME:
                    return ReturnCharacterString(VENDOR_NAME, value, valueElementCount, maxElementCount, encodingType);
                case PROPERTY_IDENTIFIER_MODEL_NAME:
                    return ReturnCharacterString(VIRTUAL_MODEL_NAME, value, valueElementCount, maxElementCount, encodingType);
                case PROPERTY_IDENTIFIER_FIRMWARE_REVISION:
                    return ReturnCharacterString(g_firmwareRevision.c_str(), value, valueElementCount, maxElementCount, encodingType);
                case PROPERTY_IDENTIFIER_APPLICATION_SOFTWARE_VERSION:
                    return ReturnCharacterString(APP_VERSION, value, valueElementCount, maxElementCount, encodingType);
                default:
                    break;
            }
        }
        return false;
    }

    // --- The GATEWAY device --------------------------------------------------
    if (deviceInstance != g_deviceInstance) {
        return false;
    }

    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT && useArrayIndex) {
        static const char* const stateText[] = { "On", "Off", "Auto" };
        if (propertyArrayIndex >= 1 && propertyArrayIndex <= MULTI_STATE_INPUT_NUMBER_OF_STATES) {
            return ReturnCharacterString(stateText[propertyArrayIndex - 1], value,
                                         valueElementCount, maxElementCount, encodingType);
        }
        *errorCode = ERROR_CODE_INVALID_ARRAY_INDEX;
        return false;
    }

    if (propertyIdentifier == PROPERTY_IDENTIFIER_OBJECT_NAME) {
        if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
            return ReturnCharacterString(DEVICE_NAME, value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == ANALOG_INPUT_INSTANCE) {
            return ReturnCharacterString("Bronze", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_BINARY_INPUT && objectInstance == BINARY_INPUT_INSTANCE) {
            return ReturnCharacterString("Emerald", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT && objectInstance == MULTI_STATE_INPUT_INSTANCE) {
            return ReturnCharacterString("Hot Pink", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_ANALOG_OUTPUT && objectInstance == ANALOG_OUTPUT_INSTANCE) {
            return ReturnCharacterString("Chartreuse", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_BINARY_OUTPUT && objectInstance == BINARY_OUTPUT_INSTANCE) {
            return ReturnCharacterString("Fuchsia", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT && objectInstance == MULTI_STATE_OUTPUT_INSTANCE) {
            return ReturnCharacterString("Indigo", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
            return ReturnCharacterString("Vermilion", value, valueElementCount, maxElementCount, encodingType);
        }
    }

    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
        switch (propertyIdentifier) {
            case PROPERTY_IDENTIFIER_DESCRIPTION:
                return ReturnCharacterString(DEVICE_DESCRIPTION, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_VENDOR_NAME:
                return ReturnCharacterString(VENDOR_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_MODEL_NAME:
                return ReturnCharacterString(MODEL_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_FIRMWARE_REVISION:
                return ReturnCharacterString(g_firmwareRevision.c_str(), value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_APPLICATION_SOFTWARE_VERSION:
                return ReturnCharacterString(APP_VERSION, value, valueElementCount, maxElementCount, encodingType);
            default:
                break;
        }
    }

    return false;
}

// -----------------------------------------------------------------------------
// 2b. Property "set" callbacks - DS-WP-B. Only the GATEWAY has writable
// objects (the commandable outputs); the virtual device's Analog Input is
// read-only, exactly like the gateway's own Analog Input 1.
// -----------------------------------------------------------------------------

bool SetPropertyReal(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     const float value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex, const uint8_t priority,
                     uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    Commandable* c = GetCommandable(deviceInstance, objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_ANALOG_OUTPUT &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        CommandWrite(c, priority, (double)value);
        printf("WriteProperty: Analog Output %u (Chartreuse) <- %.2f @ priority %u\n",
               objectInstance, value, EffectivePriority(priority));
        return true;
    }
    return false;
}

bool SetPropertyEnumerated(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           const uint32_t value, const bool useArrayIndex,
                           const uint32_t propertyArrayIndex, const uint8_t priority,
                           uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    Commandable* c = GetCommandable(deviceInstance, objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_BINARY_OUTPUT &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        if (value > 1) {
            *errorCode = ERROR_CODE_VALUE_OUT_OF_RANGE;
            return false;
        }
        CommandWrite(c, priority, (double)value);
        printf("WriteProperty: Binary Output %u (Fuchsia) <- %s @ priority %u\n",
               objectInstance, value ? "active" : "inactive", EffectivePriority(priority));
        return true;
    }
    return false;
}

bool SetPropertyUnsignedInteger(const uint32_t deviceInstance, const uint16_t objectType,
                                const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                const uint32_t value, const bool useArrayIndex,
                                const uint32_t propertyArrayIndex, const uint8_t priority,
                                uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    Commandable* c = GetCommandable(deviceInstance, objectType, objectInstance);
    if (c != NULL && objectType == OBJECT_TYPE_MULTI_STATE_OUTPUT &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        if (value < 1 || value > MULTI_STATE_OUTPUT_NUMBER_OF_STATES) {
            *errorCode = ERROR_CODE_VALUE_OUT_OF_RANGE;
            return false;
        }
        CommandWrite(c, priority, (double)value);
        printf("WriteProperty: Multi-State Output %u (Indigo) <- state %u @ priority %u\n",
               objectInstance, value, EffectivePriority(priority));
        return true;
    }
    return false;
}

bool SetPropertyNull(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     const bool useArrayIndex, const uint32_t propertyArrayIndex,
                     const uint8_t priority, uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    Commandable* c = GetCommandable(deviceInstance, objectType, objectInstance);
    if (c != NULL && propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        CommandRelinquish(c, priority);
        printf("WriteProperty: relinquished %s %u @ priority %u\n",
               objectType == OBJECT_TYPE_ANALOG_OUTPUT ? "Analog Output" :
               objectType == OBJECT_TYPE_BINARY_OUTPUT ? "Binary Output" :
               "Multi-State Output",
               objectInstance, EffectivePriority(priority));
        return true;
    }
    return false;
}

// -----------------------------------------------------------------------------
// 2c. DeviceCommunicationControl callback (DM-DCC-B) - ported verbatim from
// B-ASC's main.cpp (see there for the full essay on the errorCode contract
// this callback alone has). Only the GATEWAY answers DeviceCommunicationControl
// - the profile card does not ask the virtual device to.
// -----------------------------------------------------------------------------
bool DeviceCommunicationControl(const uint32_t deviceInstance, const uint8_t enableDisable,
                                const char* password, const uint8_t passwordLength,
                                const bool useTimeDuration, const uint16_t timeDuration,
                                uint32_t* errorCode) {
    if (deviceInstance != g_deviceInstance) {
        // Not our device (including the virtual device, which does not answer
        // this service at all). Set *errorCode even here - a false return with
        // *errorCode unset ships "Error Code = success(84)", meaningless on the wire.
        *errorCode = ERROR_CODE_OPTIONAL_FUNCTIONALITY_NOT_SUPPORTED;
        return false;
    }

    // Check the password if this device requires one. A device with no configured
    // password (DCC_PASSWORD == "") accepts any request. Compare by LENGTH FIRST,
    // then bytes - a BACnet CharacterString may contain embedded NULs, so strcmp
    // is never safe here.
    const size_t requiredLength = strlen(DCC_PASSWORD);
    if (requiredLength > 0) {
        bool matches = (password != NULL) && (passwordLength == requiredLength);
        if (matches) {
            for (size_t i = 0; i < requiredLength; ++i) {
                if (password[i] != DCC_PASSWORD[i]) {
                    matches = false;
                    break;
                }
            }
        }
        if (!matches) {
            printf("DeviceCommunicationControl: REJECTED (password failure)\n");
            *errorCode = ERROR_CODE_PASSWORD_FAILURE;
            return false;
        }
    }

    const char* action = (enableDisable == DCC_ENABLE) ? "enable (resume communication)" :
                         (enableDisable == DCC_DISABLE) ? "disable (1) - DEPRECATED, the stack will reject this" :
                         (enableDisable == DCC_DISABLE_INITIATION) ? "disable-initiation (keep responding)" :
                         "unknown";
    if (useTimeDuration) {
        printf("DeviceCommunicationControl: %s for %u minute(s)\n", action, timeDuration);
    } else {
        printf("DeviceCommunicationControl: %s (indefinitely)\n", action);
    }
    return true;
}

// -----------------------------------------------------------------------------
// 2d. Announce both devices (start-up and the 'r' key)
// -----------------------------------------------------------------------------
static void AnnounceBothDevices() {
    CASExampleHelper::SendIAm(g_deviceInstance, NETWORK_PORT_INSTANCE);
    CASExampleHelper::SendIAm(VIRTUAL_DEVICE_INSTANCE, NETWORK_PORT_INSTANCE);
    printf("FYI: I-Am broadcast for the gateway (Device %u) and the virtual device "
           "(Device %u).\n", g_deviceInstance, VIRTUAL_DEVICE_INSTANCE);
}

// -----------------------------------------------------------------------------
// 3. main()
// -----------------------------------------------------------------------------
int main(int argc, char** argv) {
    setvbuf(stdout, NULL, _IONBF, 0);

    if (!LoadBACnetFunctions()) {
        fprintf(stderr, "Error: failed to load the CAS BACnet Stack: %s\n",
                CASBACnetStackAdapter_LastError());
        return 1;
    }

    // g_firmwareRevision (Device object property 44) - see its own doc
    // comment above for why this is the STACK's version, not this example's
    // own (that's Application_Software_Version/APP_VERSION instead). Must
    // happen after LoadBACnetFunctions() (these getters ARE some of the
    // functions it loads) and before the Device object is ever readable.
    {
        char buf[32];
        snprintf(buf, sizeof(buf), "%u.%u.%u.%u",
                 BACnetStack_GetAPIMajorVersion(), BACnetStack_GetAPIMinorVersion(),
                 BACnetStack_GetAPIPatchVersion(), BACnetStack_GetAPIBuildVersion());
        g_firmwareRevision = buf;
    }

    if (CASExampleHelper::HandleHelpAndVersionArgs(argc, argv, APP_NAME, APP_VERSION)) {
        return 0;
    }
    const uint16_t port = CASExampleHelper::ParsePortArg(argc, argv, 47808);
    g_deviceInstance = CASExampleHelper::ParseDeviceIdArg(argc, argv, g_deviceInstance);
    CASExampleHelper::PrintVersion(APP_NAME, APP_VERSION);

    // --- Bind the BACnet/IP socket (one port serves BOTH devices) -----------
    if (!CASExampleHelper::SetupUDP(port)) {
        return 1;
    }
    g_bacnetIpUdpPort = port;
    if (!CASExampleHelper::GetLocalIPv4(g_ipAddress, g_ipSubnetMask)) {
        printf("FYI: could not read a local IPv4 address; Network Port IP_Address "
               "will report 0.0.0.0.\n");
    }

    // --- Register callbacks --------------------------------------------------
    CASExampleHelper::SetNetworkPortInstance(NETWORK_PORT_INSTANCE);
    CASExampleHelper::RegisterCommonCallbacks();
    BACnetStack_RegisterCallbackGetPropertyReal(GetPropertyReal);
    BACnetStack_RegisterCallbackGetPropertyEnumerated(GetPropertyEnumerated);
    BACnetStack_RegisterCallbackGetPropertyUnsignedInteger(GetPropertyUnsignedInteger);
    BACnetStack_RegisterCallbackGetPropertyCharacterString(GetPropertyCharString);
    BACnetStack_RegisterCallbackGetPropertyBool(GetPropertyBool);
    BACnetStack_RegisterCallbackGetPropertyOctetString(GetPropertyOctetString);
    BACnetStack_RegisterCallbackSetPropertyReal(SetPropertyReal);
    BACnetStack_RegisterCallbackSetPropertyEnumerated(SetPropertyEnumerated);
    BACnetStack_RegisterCallbackSetPropertyUnsignedInteger(SetPropertyUnsignedInteger);
    BACnetStack_RegisterCallbackSetPropertyNull(SetPropertyNull);
    BACnetStack_RegisterCallbackDeviceCommunicationControl(DeviceCommunicationControl);

    // --- Create the GATEWAY device --------------------------------------------
    if (!BACnetStack_AddDevice(g_deviceInstance)) {
        printf("Error: Failed to add the Device %u.\n", g_deviceInstance);
        return 1;
    }

    // DS-RP-B, DS-WP-B, DM-DCC-B.
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_READ_PROPERTY, true)) {
        printf("Error: Failed to enable the ReadProperty service.\n");
        return 1;
    }
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WRITE_PROPERTY, true)) {
        printf("Error: Failed to enable the WriteProperty service.\n");
        return 1;
    }
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_DEVICE_COMMUNICATION_CONTROL, true)) {
        printf("Error: Failed to enable the DeviceCommunicationControl service.\n");
        return 1;
    }
    // DM-DDB-B, DM-DOB-B: Who-Is/I-Am, Who-Has/I-Have.
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WHO_IS, true) ||
        !BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_I_AM, true) ||
        !BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WHO_HAS, true) ||
        !BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_I_HAVE, true)) {
        printf("Error: Failed to enable the discovery services (Who-Is/I-Am, Who-Has/I-Have).\n");
        return 1;
    }

    // --- Add the GATEWAY's read-only sensor objects ---------------------------
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_ANALOG_INPUT, ANALOG_INPUT_INSTANCE)) {
        printf("Error: Failed to add Analog Input %u (Bronze).\n", ANALOG_INPUT_INSTANCE);
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_BINARY_INPUT, BINARY_INPUT_INSTANCE)) {
        printf("Error: Failed to add Binary Input %u (Emerald).\n", BINARY_INPUT_INSTANCE);
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT, MULTI_STATE_INPUT_INSTANCE)) {
        printf("Error: Failed to add Multi-State Input %u (Hot Pink).\n", MULTI_STATE_INPUT_INSTANCE);
        return 1;
    }

    // --- Add the GATEWAY's commandable OUTPUT objects --------------------------
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_ANALOG_OUTPUT, ANALOG_OUTPUT_INSTANCE)) {
        printf("Error: Failed to add Analog Output %u (Chartreuse).\n", ANALOG_OUTPUT_INSTANCE);
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_BINARY_OUTPUT, BINARY_OUTPUT_INSTANCE)) {
        printf("Error: Failed to add Binary Output %u (Fuchsia).\n", BINARY_OUTPUT_INSTANCE);
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_OUTPUT, MULTI_STATE_OUTPUT_INSTANCE)) {
        printf("Error: Failed to add Multi-State Output %u (Indigo).\n", MULTI_STATE_OUTPUT_INSTANCE);
        return 1;
    }

    // --- Add the GATEWAY's Network Port object --------------------------------
    if (!BACnetStack_AddNetworkPortObject(
            g_deviceInstance, NETWORK_PORT_INSTANCE,
            NETWORK_PORT_NETWORK_TYPE_IPV4,
            NETWORK_PORT_PROTOCOL_LEVEL_BACNET_APPLICATION,
            0,  // networkNumber: not configured
            NETWORK_NUMBER_QUALITY_UNKNOWN,
            NETWORK_PORT_REFERENCE_PORT_NONE)) {
        printf("Error: Failed to add Network Port 1 (Vermilion).\n");
        return 1;
    }

    // --- Enable the OPTIONAL properties we choose to expose on the GATEWAY ----
    if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_DEVICE,
                                        g_deviceInstance, PROPERTY_IDENTIFIER_DESCRIPTION, true)) {
        printf("Error: Failed to enable Description on the Device object.\n");
        return 1;
    }
    if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT,
                                        MULTI_STATE_INPUT_INSTANCE, PROPERTY_IDENTIFIER_STATE_TEXT, true)) {
        printf("Error: Failed to enable State_Text on Multi-State Input 1 (Hot Pink).\n");
        return 1;
    }

    // --- Make the GATEWAY's output objects commandable -------------------------
    struct CommandableObject { uint16_t type; uint32_t instance; };
    const CommandableObject outputs[] = {
        { OBJECT_TYPE_ANALOG_OUTPUT,      ANALOG_OUTPUT_INSTANCE },
        { OBJECT_TYPE_BINARY_OUTPUT,      BINARY_OUTPUT_INSTANCE },
        { OBJECT_TYPE_MULTI_STATE_OUTPUT, MULTI_STATE_OUTPUT_INSTANCE },
    };
    for (size_t i = 0; i < sizeof(outputs) / sizeof(outputs[0]); ++i) {
        if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, outputs[i].type, outputs[i].instance,
                                            PROPERTY_IDENTIFIER_PRIORITY_ARRAY, true) ||
            !BACnetStack_SetPropertyEnabled(g_deviceInstance, outputs[i].type, outputs[i].instance,
                                            PROPERTY_IDENTIFIER_RELINQUISH_DEFAULT, true) ||
            !BACnetStack_SetPropertyWritable(g_deviceInstance, outputs[i].type, outputs[i].instance,
                                             PROPERTY_IDENTIFIER_PRESENT_VALUE, true)) {
            printf("Error: Failed to make object type %u instance %u commandable.\n",
                   outputs[i].type, outputs[i].instance);
            return 1;
        }
    }

    // --- F-GATEWAY (GW-VN-B): create the virtual network and the virtual device ----
    //
    // BACnetStack_AddVirtualNetwork turns the GATEWAY into a virtual router and
    // creates a Network Port object (VIRTUAL_NETWORK_PORT_INSTANCE) for the new
    // virtual network - fully populated by the stack, nothing for this
    // application's Get*Property callbacks to serve. Must be called after
    // BACnetStack_AddDevice and names the SAME deviceInstance passed there.
    if (!BACnetStack_AddVirtualNetwork(g_deviceInstance, VIRTUAL_NETWORK_NUMBER, VIRTUAL_NETWORK_PORT_INSTANCE)) {
        printf("Error: Failed to add virtual network %u (built without STACK_OPTION_VIRTUAL_ROUTER?).\n",
               (unsigned)VIRTUAL_NETWORK_NUMBER);
        return 1;
    }
    // BACnetStack_AddDeviceToVirtualNetwork adds the VIRTUAL device itself, on
    // the network just created. From here on VIRTUAL_DEVICE_INSTANCE is a full
    // device: BACnetStack_AddObject/SetServiceEnabled/SetPropertyEnabled all take
    // it directly as their deviceInstance parameter.
    if (!BACnetStack_AddDeviceToVirtualNetwork(VIRTUAL_DEVICE_INSTANCE, VIRTUAL_NETWORK_NUMBER)) {
        printf("Error: Failed to add the virtual device %u to virtual network %u.\n",
               VIRTUAL_DEVICE_INSTANCE, (unsigned)VIRTUAL_NETWORK_NUMBER);
        return 1;
    }
    // The virtual device answers ReadProperty on itself (DS-RP-B) and discovery
    // (DM-DDB-B/DM-DOB-B) - the same services the gateway enables above, but this
    // is a SEPARATE device object with its own service-enabled bits.
    if (!BACnetStack_SetServiceEnabled(VIRTUAL_DEVICE_INSTANCE, SERVICE_READ_PROPERTY, true) ||
        !BACnetStack_SetServiceEnabled(VIRTUAL_DEVICE_INSTANCE, SERVICE_WHO_IS, true) ||
        !BACnetStack_SetServiceEnabled(VIRTUAL_DEVICE_INSTANCE, SERVICE_I_AM, true) ||
        !BACnetStack_SetServiceEnabled(VIRTUAL_DEVICE_INSTANCE, SERVICE_WHO_HAS, true) ||
        !BACnetStack_SetServiceEnabled(VIRTUAL_DEVICE_INSTANCE, SERVICE_I_HAVE, true)) {
        printf("Error: Failed to enable services on the virtual device %u.\n", VIRTUAL_DEVICE_INSTANCE);
        return 1;
    }
    // The virtual device's own Analog Input 1 (Bronze) - proves GW-VN-B by
    // giving the represented device something to actually be read.
    if (!BACnetStack_AddObject(VIRTUAL_DEVICE_INSTANCE, OBJECT_TYPE_ANALOG_INPUT, VIRTUAL_ANALOG_INPUT_INSTANCE)) {
        printf("Error: Failed to add Analog Input %u (Bronze) to the virtual device %u.\n",
               VIRTUAL_ANALOG_INPUT_INSTANCE, VIRTUAL_DEVICE_INSTANCE);
        return 1;
    }
    if (!BACnetStack_SetPropertyEnabled(VIRTUAL_DEVICE_INSTANCE, OBJECT_TYPE_DEVICE,
                                        VIRTUAL_DEVICE_INSTANCE, PROPERTY_IDENTIFIER_DESCRIPTION, true)) {
        printf("Error: Failed to enable Description on the virtual Device object.\n");
        return 1;
    }

    // Who-Is is answered automatically for both devices (DM-DDB-B). Broadcast an
    // unsolicited I-Am for EACH (DM-DDB-A-equivalent start-up courtesy, though
    // only DM-DDB-B is claimed - see the README for why an initial I-Am does not
    // by itself claim DM-DDB-A).
    AnnounceBothDevices();

    printf("FYI: Device %u (\"%s\") ready. Vendor ID %u. Gateways virtual Device %u "
           "(\"%s\") on virtual network %u. Press 'h' for help.\n",
           g_deviceInstance, DEVICE_NAME, VENDOR_IDENTIFIER,
           VIRTUAL_DEVICE_INSTANCE, VIRTUAL_DEVICE_NAME, (unsigned)VIRTUAL_NETWORK_NUMBER);

    // --- Run the stack ------------------------------------------------------
    bool running = true;
    while (running) {
        BACnetStack_Tick();

        switch (CASExampleHelper::PollKey()) {
            case CASExampleHelper::KeyCommand::Help:
                CASExampleHelper::PrintHelp(APP_NAME, APP_VERSION);
                break;
            case CASExampleHelper::KeyCommand::Quit:
                running = false;
                break;
            case CASExampleHelper::KeyCommand::ArrowUp:
                g_analogInput1Value += 1.1f;
                printf("Analog Input 1 (Bronze) = %.1f C\n", g_analogInput1Value);
                break;
            case CASExampleHelper::KeyCommand::ArrowDown:
                g_analogInput1Value -= 1.1f;
                printf("Analog Input 1 (Bronze) = %.1f C\n", g_analogInput1Value);
                break;
            case CASExampleHelper::KeyCommand::RouterAnnounce:
                AnnounceBothDevices();
                break;
            case CASExampleHelper::KeyCommand::None:
            default:
                break;
        }

#if defined(_WIN32)
        Sleep(1);
#else
        usleep(1000);
#endif
    }

    CASExampleHelper::RestoreInput();
    CASExampleHelper::ShutdownUDP();
    return 0;
}
